### PR TITLE
Nuget packages restore (fix for #13)

### PR DESCRIPTION
**Pull request by takemyoxygen**
A pull request for #13. Downloads packages and generates references to downloaded dlls using Paket API.

### CODE REVIEW

**Comment by tpetricek** [comment]
Wow, this looks really cool!! I'll do a more proper review soon.

**Comment by takemyoxygen** [comment]
Thanks, I'll try to finish Update snippet part this week.

**Comment by takemyoxygen** [comment]
@tpetricek I added restoring packages when updating an existing snipped. I also ensured that new compiler options are appended to default options instead of overriding them (my solution looks pretty hacky, maybe you can come up with a better one since I guess you know FSharp.Formatting pretty well :smile:).

One more thing: when `FSharp.Data` package is referenced, I get the following error:

```
The type provider 'ProviderImplementation.JsonProvider' reported an error: 
The type provider constructor has thrown an exception: API restriction: 
The assembly 'file:///C:\takemyoxygen\code\FsSnip.Website\temp\16cce71b-57df-4edb-9c5b-48825d0ce471\packages\FSharp.Data\lib\net40\FSharp.Data.dll'
has already loaded from a different location. It cannot be loaded from a new location within the same appdomain.
```

Any thougts on that?

**Comment by tpetricek** [comment]
I'm finally getting back to this - sorry for the horrible delay :-). It works like a charm, thanks so much for doing this!!

As for FSharp.Data, this is because we already have a reference to FSharp.Data in the project - and for type providers, we cannot load the library from another place. I'll add a hack to just load the FSharp.Data that we already have - this is really only going to affect this one library, so it should be fine.

**Pull request merged**
