### PR TITLE
Azure Blob Storage

### PR DESCRIPTION
**Pull request by ilmaestro**
Here's my first draft of getting Azure blob storage up and running with the AzureStorageTypeProvider. Had to up the framework to 4.5.1, hopefully that won't cause any issues with deployment.  Otherwise, this version is working for loading snippets from blob storage.  I haven't yet tested the insert functions.  I ran out of time this week, but should be able to finish this on Monday or Tuesday next week.  

I'm curious the best way to use the JsonProvider with Azure - my current solution relies on being able to load the json sample file or it's structure, and then uses the Parse method to load the index.json text from azure blob storage. I think this is fine, but want to make sure. 

F# puts the fun in functional.
-ryan

### CODE REVIEW

**Comment by ilmaestro** [comment]
working version ready.  Did a lot of cleanup and made it easy to switch between Local and Azure storage.

**Comment by tpetricek** [comment]
Sorry for the long delay here - I had two deadlines for various things in the last two weeks :-).

The code looks pretty good to me, so I'm going to merge this and I'll see if I can actually get this to run on Azure! Once we have a basic version running somewhere live, that'll be a cool milestone!

**Comment by tpetricek** [comment]
This is looking pretty sweet, just uploading all the data into Azure using your nice script :-p

**Comment by ilmaestro** [comment]
I'm glad to hear that's working! Let me know if there are any tweaks that
need to be made.

**Comment by tpetricek** [comment]
It took a long time (holidays + work!) but I finally deployed this to Azure: http://fssnip.azurewebsites.net/
I did a bit of refactoring, but the core of the code is still there - so thanks a lot for the contribution :-)

Also, now that it's running on Azure, it will be a lot more fun to complete the rest - any PR into master will immediately affect the web site!

**Pull request merged**
