### PR TITLE
Update to suave 1.0

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
image

**Comment by forki** [comment]
ok `paket update nuget Suave.DotLiquid` fixed that.

**Comment by haf** [comment]
Sounds like you got an old Suave dll around there somewhere.

CEO qvitoo
+46737532718
https://qvitoo.com

**Comment by forki** [comment]
It was incompatible Suave.DotLiquid. but all works now. thanks. 
Trasition was relatively easy.

```
-      bindings = [ HttpBinding.mk' HTTP  "127.0.0.1" port ] }
+      bindings = [ HttpBinding.mkSimple HTTP  "127.0.0.1" port ] }
```

is that correct?

**Comment by haf** [comment]
Looks good.

**Comment by tpetricek** [comment]
Thanks :) upgraded now!

**Pull request merged**
