### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by forki**
Since https://github.com/forki/suaveondocker works, I'm now trying to get fssnip running on docker.

This is what I did:

1) copy fssnip data in data folder as described in readme
2) added Dockerfile and app.docker.fsx
3) build docker image with `docker build -t forki/fssnip:0.1 .`
4) run docker container with `docker run -d -p 8080:8080 forki/fssnip:0.1`
5) go to website:

image

Open questions:

1) <strike>I needed to inline app.fsx in app.docker.fsx, because somehow fsharpi was not finding what app is in the last line of app.docker.fsx (@dsyme any ideas why #load might work, but the outer script doesn't find the binding from the inner script?)</strike>
2) <strike>my website is missing lots of files (or the links are broken) @haf do you see why this could be? </strike>
3) we should some how automate the copy of the data folder with wget in the dockerfile. but I didn't find a deep link to the original zip

### CODE REVIEW

**Comment by haf** [comment]
I think you may be copying everything to the root of the file system, so you should create a directory and do a `WORKDIR`.

**Comment by forki** [comment]
@haf sorry again about me being noob. I tried in 8d723ed, but site looks the same.

**Comment by haf** [comment]
Can you try to turn on Suave's logging?

**Comment by forki** [comment]
in 66c51a8 I enabled logging.

with `docker logs` I get the following after browsing to the main page

```
FSharp.Formatting Information: 0 : FSharp.Formatting Logging setup!
Yaaf.FSharp.Scriping Information: 0 : Yaaf.FSharp.Scripting Logging setup!
[D] 2015-11-04T12:47:28.3691260Z: 192.168.99.1 1 - [04/Nov/2015:12:47:28 Z] "GET / HTTP/1.1" 404 0 [Suave.Http.web-requests]
[D] 2015-11-04T12:47:28.4950590Z: 192.168.99.1 1 - [04/Nov/2015:12:47:28 Z] "GET / HTTP/1.1" 200 11441 [Suave.Http.web-requests]
[D] 2015-11-04T12:47:28.5615010Z: 192.168.99.1 1 - [04/Nov/2015:12:47:28 Z] "GET /lib/jquery.js HTTP/1.1" 404 0 [Suave.Http.web-requests]
[E] 2015-11-04T12:47:28.5815030Z: request failed [Suave.Web.defaultErrorHandler] exn:
System.NullReferenceException: Object reference not set to an instance of an object
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in <filename unknown>:0 
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in <filename unknown>:0 
  at Suave.Http+choose@48-1.Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[Microsoft.FSharp.Core.FSharpOption`1[Suave.Types+HttpContext],Microsoft.FSharp.Core.Unit].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) [0x00000] in <filename unknown>:0 
[D] 2015-11-04T12:47:28.5822580Z: 192.168.99.1 1 - [04/Nov/2015:12:47:28 Z] "GET /lib/bootstrap.min.css HTTP/1.1" 404 0 [Suave.Http.web-requests]
[E] 2015-11-04T12:47:28.5824280Z: request failed [Suave.Web.defaultErrorHandler] exn:
System.NullReferenceException: Object reference not set to an instance of an object
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in <filename unknown>:0 
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in <filename unknown>:0 
  at Suave.Http+choose@48-1.Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[Microsoft.FSharp.Core.FSharpOption`1[Suave.Types+HttpContext],Microsoft.FSharp.Core.Unit].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) [0x00000] in <filename unknown>:0 
[D] 2015-11-04T12:47:28.5830110Z: 192.168.99.1 1 - [04/Nov/2015:12:47:28 Z] "GET /lib/bootstrap.min.js HTTP/1.1" 404 0 [Suave.Http.web-requests]
[E] 2015-11-04T12:47:28.5831250Z: request failed [Suave.Web.defaultErrorHandler] exn:
System.NullReferenceException: Object reference not set to an instance of an object
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in <filename unknown>:0 
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in <filename unknown>:0 
  at Suave.Http+choose@48-1.Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[Microsoft.FSharp.Core.FSharpOption`1[Suave.Types+HttpContext],Microsoft.FSharp.Core.Unit].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) [0x00000] in <filename unknown>:0 
[D] 2015-11-04T12:47:28.5834500Z: 192.168.99.1 1 - [04/Nov/2015:12:47:28 Z] "GET /content/style.css HTTP/1.1" 404 0 [Suave.Http.web-requests]
[E] 2015-11-04T12:47:28.5835660Z: request failed [Suave.Web.defaultErrorHandler] exn:
System.NullReferenceException: Object reference not set to an instance of an object
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in <filename unknown>:0 
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in <filename unknown>:0 
  at Suave.Http+choose@48-1.Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[Microsoft.FSharp.Core.FSharpOption`1[Suave.Types+HttpContext],Microsoft.FSharp.Core.Unit].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) [0x00000] in <filename unknown>:0 
[D] 2015-11-04T12:47:28.5881680Z: 192.168.99.1 1 - [04/Nov/2015:12:47:28 Z] "GET /content/snippets.css HTTP/1.1" 404 0 [Suave.Http.web-requests]
[E] 2015-11-04T12:47:28.5884500Z: request failed [Suave.Web.defaultErrorHandler] exn:
System.NullReferenceException: Object reference not set to an instance of an object
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in <filename unknown>:0 
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in <filename unknown>:0 
  at Suave.Http+choose@48-1.Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[Microsoft.FSharp.Core.FSharpOption`1[Suave.Types+HttpContext],Microsoft.FSharp.Core.Unit].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) [0x00000] in <filename unknown>:0 
[D] 2015-11-04T12:47:28.5947210Z: 192.168.99.1 1 - [04/Nov/2015:12:47:28 Z] "GET /content/tips.js HTTP/1.1" 404 0 [Suave.Http.web-requests]
[E] 2015-11-04T12:47:28.5949440Z: request failed [Suave.Web.defaultErrorHandler] exn:
System.NullReferenceException: Object reference not set to an instance of an object
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in <filename unknown>:0 
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in <filename unknown>:0 
  at Suave.Http+choose@48-1.Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[Microsoft.FSharp.Core.FSharpOption`1[Suave.Types+HttpContext],Microsoft.FSharp.Core.Unit].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) [0x00000] in <filename unknown>:0 
[D] 2015-11-04T12:47:28.6405400Z: 192.168.99.1 1 - [04/Nov/2015:12:47:28 Z] "GET /img/fswebsnippets.png HTTP/1.1" 404 0 [Suave.Http.web-requests]
[E] 2015-11-04T12:47:28.6407480Z: request failed [Suave.Web.defaultErrorHandler] exn:
System.NullReferenceException: Object reference not set to an instance of an object
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in <filename unknown>:0 
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in <filename unknown>:0 
  at Suave.Http+choose@48-1.Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[Microsoft.FSharp.Core.FSharpOption`1[Suave.Types+HttpContext],Microsoft.FSharp.Core.Unit].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) [0x00000] in <filename unknown>:0 
[D] 2015-11-04T12:47:28.7663140Z: 192.168.99.1 1 - [04/Nov/2015:12:47:28 Z] "GET /favicon.ico HTTP/1.1" 404 0 [Suave.Http.web-requests]
[E] 2015-11-04T12:47:28.7668120Z: request failed [Suave.Web.defaultErrorHandler] exn:
System.NullReferenceException: Object reference not set to an instance of an object
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in <filename unknown>:0 
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in <filename unknown>:0 
  at Suave.Http+choose@48-1.Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[Microsoft.FSharp.Core.FSharpOption`1[Suave.Types+HttpContext],Microsoft.FSharp.Core.Unit].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) [0x00000] in <filename unknown>:0 
```

**Comment by haf** [comment]
So it would seem a `pathScan` is failing. You can further improve this by running `fsharpi` with `--debug` before the filename to run, and it would be helpful to remove the lines from choose one by one until there's only a minimal repro left. But it's one with pathScan twice in it...

**Comment by forki** [comment]
cba6c68 is the last working version

27e3cea introduces the first nullpointerexception  /cc @tpetricek 

logs:

```
FSharp.Formatting Information: 0 : FSharp.Formatting Logging setup!
Yaaf.FSharp.Scriping Information: 0 : Yaaf.FSharp.Scripting Logging setup!
[D] 2015-11-04T13:24:52.8984060Z: 192.168.99.1 1 - [04/Nov/2015:01:24:52 Z] "GET / HTTP/1.1" 404 0 [Suave.Http.web-requests]
[D] 2015-11-04T13:24:53.0445060Z: 192.168.99.1 1 - [04/Nov/2015:01:24:53 Z] "GET / HTTP/1.1" 200 11441 [Suave.Http.web-requests]
[D] 2015-11-04T13:24:53.0946880Z: 192.168.99.1 1 - [04/Nov/2015:01:24:53 Z] "GET /lib/jquery.js HTTP/1.1" 404 0 [Suave.Http.web-requests]
[E] 2015-11-04T13:24:53.1165430Z: request failed [Suave.Web.defaultErrorHandler] exn:
System.NullReferenceException: Object reference not set to an instance of an object
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in /Users/h/dev/haf/suave/src/Suave/Http.fs:429 
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x0002f] in /Users/h/dev/haf/suave/src/Suave/Http.fs:432 
  at Suave.Http+choose@48-1.Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00000] in /Users/h/dev/haf/suave/src/Suave/Http.fs:51 
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[Microsoft.FSharp.Core.FSharpOption`1[Suave.Types+HttpContext],Microsoft.FSharp.Core.Unit].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) [0x0002b] in /builddir/build/BUILD/fsharp-4.0.0.3/src/fsharp/FSharp.Core/control.fs:855 
[D] 2015-11-04T13:24:53.1175030Z: 192.168.99.1 1 - [04/Nov/2015:01:24:53 Z] "GET /lib/bootstrap.min.css HTTP/1.1" 404 0 [Suave.Http.web-requests]
[E] 2015-11-04T13:24:53.1176920Z: request failed [Suave.Web.defaultErrorHandler] exn:
System.NullReferenceException: Object reference not set to an instance of an object
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in /Users/h/dev/haf/suave/src/Suave/Http.fs:429 
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x0002f] in /Users/h/dev/haf/suave/src/Suave/Http.fs:432 
  at Suave.Http+choose@48-1.Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00000] in /Users/h/dev/haf/suave/src/Suave/Http.fs:51 
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[Microsoft.FSharp.Core.FSharpOption`1[Suave.Types+HttpContext],Microsoft.FSharp.Core.Unit].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) [0x0002b] in /builddir/build/BUILD/fsharp-4.0.0.3/src/fsharp/FSharp.Core/control.fs:855 
[D] 2015-11-04T13:24:53.1180870Z: 192.168.99.1 1 - [04/Nov/2015:01:24:53 Z] "GET /lib/bootstrap.min.js HTTP/1.1" 404 0 [Suave.Http.web-requests]
[E] 2015-11-04T13:24:53.1181890Z: request failed [Suave.Web.defaultErrorHandler] exn:
System.NullReferenceException: Object reference not set to an instance of an object
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in /Users/h/dev/haf/suave/src/Suave/Http.fs:429 
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x0002f] in /Users/h/dev/haf/suave/src/Suave/Http.fs:432 
  at Suave.Http+choose@48-1.Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00000] in /Users/h/dev/haf/suave/src/Suave/Http.fs:51 
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[Microsoft.FSharp.Core.FSharpOption`1[Suave.Types+HttpContext],Microsoft.FSharp.Core.Unit].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) [0x0002b] in /builddir/build/BUILD/fsharp-4.0.0.3/src/fsharp/FSharp.Core/control.fs:855 
[D] 2015-11-04T13:24:53.1185950Z: 192.168.99.1 1 - [04/Nov/2015:01:24:53 Z] "GET /content/style.css HTTP/1.1" 404 0 [Suave.Http.web-requests]
[E] 2015-11-04T13:24:53.1186870Z: request failed [Suave.Web.defaultErrorHandler] exn:
System.NullReferenceException: Object reference not set to an instance of an object
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in /Users/h/dev/haf/suave/src/Suave/Http.fs:429 
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x0002f] in /Users/h/dev/haf/suave/src/Suave/Http.fs:432 
  at Suave.Http+choose@48-1.Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00000] in /Users/h/dev/haf/suave/src/Suave/Http.fs:51 
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[Microsoft.FSharp.Core.FSharpOption`1[Suave.Types+HttpContext],Microsoft.FSharp.Core.Unit].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) [0x0002b] in /builddir/build/BUILD/fsharp-4.0.0.3/src/fsharp/FSharp.Core/control.fs:855 
[D] 2015-11-04T13:24:53.1190310Z: 192.168.99.1 1 - [04/Nov/2015:01:24:53 Z] "GET /content/snippets.css HTTP/1.1" 404 0 [Suave.Http.web-requests]
[E] 2015-11-04T13:24:53.1191510Z: request failed [Suave.Web.defaultErrorHandler] exn:
System.NullReferenceException: Object reference not set to an instance of an object
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in /Users/h/dev/haf/suave/src/Suave/Http.fs:429 
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x0002f] in /Users/h/dev/haf/suave/src/Suave/Http.fs:432 
  at Suave.Http+choose@48-1.Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00000] in /Users/h/dev/haf/suave/src/Suave/Http.fs:51 
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[Microsoft.FSharp.Core.FSharpOption`1[Suave.Types+HttpContext],Microsoft.FSharp.Core.Unit].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) [0x0002b] in /builddir/build/BUILD/fsharp-4.0.0.3/src/fsharp/FSharp.Core/control.fs:855 
[D] 2015-11-04T13:24:53.1195910Z: 192.168.99.1 1 - [04/Nov/2015:01:24:53 Z] "GET /content/tips.js HTTP/1.1" 404 0 [Suave.Http.web-requests]
[E] 2015-11-04T13:24:53.1196910Z: request failed [Suave.Web.defaultErrorHandler] exn:
System.NullReferenceException: Object reference not set to an instance of an object
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in /Users/h/dev/haf/suave/src/Suave/Http.fs:429 
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x0002f] in /Users/h/dev/haf/suave/src/Suave/Http.fs:432 
  at Suave.Http+choose@48-1.Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00000] in /Users/h/dev/haf/suave/src/Suave/Http.fs:51 
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[Microsoft.FSharp.Core.FSharpOption`1[Suave.Types+HttpContext],Microsoft.FSharp.Core.Unit].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) [0x0002b] in /builddir/build/BUILD/fsharp-4.0.0.3/src/fsharp/FSharp.Core/control.fs:855 
[D] 2015-11-04T13:24:53.1305490Z: 192.168.99.1 1 - [04/Nov/2015:01:24:53 Z] "GET /img/fswebsnippets.png HTTP/1.1" 404 0 [Suave.Http.web-requests]
[E] 2015-11-04T13:24:53.1307520Z: request failed [Suave.Web.defaultErrorHandler] exn:
System.NullReferenceException: Object reference not set to an instance of an object
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in /Users/h/dev/haf/suave/src/Suave/Http.fs:429 
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x0002f] in /Users/h/dev/haf/suave/src/Suave/Http.fs:432 
  at Suave.Http+choose@48-1.Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00000] in /Users/h/dev/haf/suave/src/Suave/Http.fs:51 
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[Microsoft.FSharp.Core.FSharpOption`1[Suave.Types+HttpContext],Microsoft.FSharp.Core.Unit].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) [0x0002b] in /builddir/build/BUILD/fsharp-4.0.0.3/src/fsharp/FSharp.Core/control.fs:855 
[D] 2015-11-04T13:24:53.1536210Z: 192.168.99.1 1 - [04/Nov/2015:01:24:53 Z] "GET /favicon.ico HTTP/1.1" 404 0 [Suave.Http.web-requests]
[E] 2015-11-04T13:24:53.1540710Z: request failed [Suave.Web.defaultErrorHandler] exn:
System.NullReferenceException: Object reference not set to an instance of an object
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x00000] in /Users/h/dev/haf/suave/src/Suave/Http.fs:429 
  at Suave.Http+Applicatives+pathScan@429[Microsoft.FSharp.Core.FSharpFunc`2[System.String,System.Object],System.Object,System.Object,System.Object,System.String].Invoke (Suave.HttpContext r) [0x0002f] in /Users/h/dev/haf/suave/src/Suave/Http.fs:432 
  at Suave.Http+choose@48-1.Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00000] in /Users/h/dev/haf/suave/src/Suave/Http.fs:51 
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@851[Microsoft.FSharp.Core.FSharpOption`1[Suave.Types+HttpContext],Microsoft.FSharp.Core.Unit].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) [0x0002b] in /builddir/build/BUILD/fsharp-4.0.0.3/src/fsharp/FSharp.Core/control.fs:855 
```

**Comment by haf** [comment]
This should be reproducible in an ordinary debugger

**Comment by forki** [comment]
it's only happening inside of the container

**Comment by forki** [comment]
I was able to track it down a bit. Only the following line that is broken

```
pathWithId "/%s" (fun id -> Snippet.showSnippet id Latest)
```

So seems I need to go deeper down that rabit hole.

**Comment by forki** [comment]
OK, now I'm lost. this change fixes the NullReferenceException and makes the site "work".
image

the only strange thing on the site is:

image

**Comment by theimowski** [comment]
Why would printf make any difference here?

**Comment by haf** [comment]
Because the F#/mono JIT interaction has some bug in it. Probably because 
it’s mono 4.0.4 and not 4.2 like is the latest stable “non stable” 
release, not yet released on package managers.

We need to decide a policy on how to deal with this sort of aping 
around. Should I make the dockerfile compile its own mono, for example?

**Comment by forki** [comment]
mhm I'm in for whatever makes this work. ;-)

**Comment by tpetricek** [comment]
I stop checking my Github spam folder and this happens! Cool stuff :-). Give me a few days though! (In the long term, it would be amazing to have a real Docker deployment for this on AWS or something as a fully working alternative to Azure.)

**Comment by forki** [comment]
It now works with the latest F# docker image!

cool

**Comment by haf** [comment]
Somehow I don't have any trouble visualising you as that guy.

**Comment by tforkmann** [comment]
Haha lol :)

Am Mittwoch, 2. Dezember 2015 schrieb Henrik Feldt :

> Somehow I don't have any trouble visualising you as that guy.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tpetricek/FsSnip.Website/pull/30#issuecomment-161429758
> .

## 

Tim Forkmann
Haubachstr. 30
10585 Berlin
0151-15813418

**Comment by haf** [comment]
Ping?

**Comment by tpetricek** [comment]
I'm happy to merge this! I suppose I'll keep using Azure Web Sites for hosting it for now though - unless someone tells me how to host it via Docker instead :)

**Comment by haf** [comment]
Sounds good!

**Comment by tpetricek** [comment]
👍 thanks for the reminder about this!

**Pull request merged**
