### PR TITLE
Update to latest FSharp.Formatting and FSCS

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Updates to latest FSCS and working around a few breaking changes cc @dsyme

### CODE REVIEW

**Comment by eiriktsarpalis** [comment]
@dsyme FWIW I couldn't use the FSharp.Formatting.Literate package since it no longer includes the CodeFormat components.

**Comment by dsyme** [comment]
@eiriktsarpalis Can you give me permission on this repo?  Also do you have permission to republish the site?

Sorry I didn't see your @dsyme btw.

**Comment by eiriktsarpalis** [comment]
> @eiriktsarpalis Can you give me permission on this repo? Also do you have permission to republish the site?

Don't have permission for neither unfortunately.

**Comment by tpetricek** [comment]
@eiriktsarpalis @dsyme You were both maintainers of this repo, but I made you admins, so you should have rights for everything now.

The site gets automatically deployed from `master`. If there was a way to share access to the relevant Azure resources with others, I'd be happy to do that, but I don't think there is. If anyone else wants to host this, I'm happy to hand it over too. It's just an Azure App service with one blob storage account. But I'm also OK to keep hosting this - whatever works best!

**Comment by eiriktsarpalis** [comment]
I'd be happy to take this on (I already have a copy of the website running in my Azure account), but perhaps it might make sense to move this under the control of the F# foundation? cc @dsyme

**Pull request merged**
