### PR TITLE
minify js before deploy as it is added to gitignore

### PR DESCRIPTION
**Pull request by kunjee17**
As dist folder added to gitignore. I have added JS minify process just before deploy process start. Sorry to break the deployment.

### CODE REVIEW

**Comment by tpetricek** [comment]
Can you do this via FAKE dependencies between targets, i.e. by adding `"JS" ==> "deploy"` - and perhaps also rename `JS` to something like `minify` so that it is more descriptive and follows the naming conventions for the targets?

**Comment by kunjee17** [comment]
@tpetricek Done. Have a look. :)

**Comment by tpetricek** [comment]
Thanks, deploy in progress :)

**Comment by kunjee17** [comment]
@tpetricek great. Funny thing this thing work on fssnip site but I also have same thing for one of my side project and it breaks every time. o_O

**Pull request merged**
