### PR TITLE
Api and update snippet

### PR DESCRIPTION
**Pull request by treefrog00**
I deleted my previous PR because my changes to make it work in Visual Studio made it stop working in Azure, and it took me a couple of hours to work out which of my commits broke it and why. Turns out I'd failed to add an extra open statement in app.azure.fsx. Would any of the buttons in the Azure portal have told me what was wrong? The only way I could figure out which commit broke it and why it was through very laborious trial and error.
1. Issue #4 says the Suave built-in functions don't work, but I have deployed my fork to Azure and it looks OK? http://fssnip-jamesjrg.azurewebsites.net/
   
   Or was the problem intermittent, or only for certain files, or something?
2. I add a handler to return 404 if the route cannot be matched. The current version will give 500 internal server errors for certain urls
3. I have added the API functions for get, get all, and PUT (#15). They are currently routed at /api, not at an API subdomain
4. Adding a new version kind of "works" (partly fixing #14), but there are numerous problems. Metadata is always overwritten with the latest version, it doesn't pay attention to whether a snippet has a password or is hidden, concurrent updates will overwrite each other, etc.
5. It now runs in Visual Studio as well as via the auto-reload script

### CODE REVIEW

**Comment by tpetricek** [comment]
Sorry again for the delay. I'm _finally_ back home with no travel plans, so will look into this.

**Comment by treefrog00** [comment]
If there's some problems I don't mind either closing this or otherwise fixing them, but it's a bit weird having an undead PR!

**Comment by tpetricek** [comment]
I just need to figure out how to setup the sub-domain in Azure, that's the only thing blocking it, sorry!

**Comment by tpetricek** [comment]
Actually, I'll look into this right now to get this in....

**Comment by tpetricek** [comment]
I merged this manually, so you're officially 7th contributor to the project. Thanks!

I did not merge the last commit (https://github.com/jamesjrg/FsSnip.Website/commit/5acf35024a2e46064cd95f9a54443e192d1a2de1), because that was causing a lot of merge issues.

I also didn't quite understand why moving the code to another file makes this work in Visual Studio. The `app.fsx` file is marked as `Compile` and so it should work (in theory).

When I hit F5 in Visual Studio it  reports a bunch of errors like:

> FSC: error FS0082: Could not resolve this reference. Could not locate the assembly "RazorEngine.dll". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. (Code=MSB3245)

Is that the same on your machine? Does that commit somehow fix this?

**Comment by treefrog00** [comment]
The change to move code into `app.fs` and `program.fs` and marking app.fsx as `Build action: None` does fix those errors, yes. These two lines upset Visual Studio:

```
#load "packages/FSharp.Azure.StorageTypeProvider/StorageTypeProvider.fsx"
#load "packages/FSharp.Formatting/FSharp.Formatting.fsx"
```

An alternative would be to change how references get loaded for those package fsx files somehow.

**Pull request closed without merging**
