### PR TITLE
Fixes #36 and a minor fix in search.js

### LINKED ISSUE #36: Block script injection in search
See #35

### PR DESCRIPTION
**Pull request by patrick-mackay**
Tomas, although the fix for the encoding was suggested already, there is a minimal fix in the search.js. Nothing critical.

### CODE REVIEW

**Comment by patrick-mackay** [comment]
I'm not sure why this thing merged the commits in the same pull request.. maybe it's normal... don't know. Surely I did something wrong using github client...

**Comment by tpetricek** [comment]
I'm finally getting back to this - sorry for the delay. I merged the PR and I'll do various clean-ups & merge it with other changes to get everything up-to-date!

GitHub only allows one pull request from each branch - you can create multiple PRs if you put different changes in different branches.

**Comment by patrick-mackay** [comment]
Thanks Tomas for the explanation.
I never knew what happened, I mean, I didn't hear from you for more than a month... Glad to know that the code was merged.
Patrick

Date: Mon, 11 Jan 2016 10:44:49 -0800

**Comment by tpetricek** [comment]
Yeah - really sorry about that. It must have been the usual storm of deadlines followed by holidays. I need to get more active core maintainers for the repo! Preferably someone with better ping :)

**Pull request merged**
