### PR TITLE
Remove 404

### PR DESCRIPTION
**Pull request by ShalokShalom**
Site is down. You may want to fill in the replacement.

### CODE REVIEW

**Comment by tpetricek** [comment]
Thanks!

Your change is absolutely right - but it might be a good opportunity to change this and recommend the FSSF slack instead. Could you tweak this to link to http://fsharp.org/guides/slack/ instead?

**Comment by ShalokShalom** [comment]
Like that?

**Comment by tpetricek** [comment]
Almost! 

The one last little change is that this is now hosted by the F# Foundation, so the new slack URL is `https://fsharp.slack.com` and the channel to join is probably `#general` (as this is all F# now).

Sorry for making it so hard to ship this small fix :-). I just realised that it's much better to point people there nowadays!

**Comment by ShalokShalom** [comment]
I like to avoid Slack, can you check if its really #general there?

**Comment by ShalokShalom** [comment]
Commit is done. I hope this help. :smiley:  
You may want to send this message to the channel:

Why do you use Slack? 
Rocketchat can import all the details of it and is open source. 
This effects the project, since the people get the impression that F-Sharp is non-free as well?

Thanks a lot

**Comment by tpetricek** [comment]
Awesome, thanks!

I recommend Slack simply because there is a large community there already - as much as I dislike it for many reasons, if anyone wants to help with fssnippets, they will find people there who can help them.

**Comment by ShalokShalom** [comment]
Here are the instructions to port your Slack data into Rocket.Chat: 
https://rocket.chat/docs/administrator-guides/import/slack/

It is also possible to [build a bridge](https://rocket.chat/docs/administrator-guides/import/slack/slackbridge), for the time between the shift. 

Thanks a lot for all, what you are doing. I am new to the community and its awesome to see, that there is a live and active community on an open source Microsoft product. Feels nice ^-^

Happy Hacking :smile:

**Pull request merged**
