### PR TITLE
implement copy link and copy source buttons in snippet details

### PR DESCRIPTION
**Pull request by abjrcode**
this resolves issue #9

### CODE REVIEW

**Comment by tpetricek** [comment]
Thanks for looking into this - I actually quite like how this looks!

Here are a few comments after playing with this a little:
- The "Copy source" button works nicely, but "Copy link" does not do anything on my machine. Not sure what's going wrong. How can I help to debug this?
- If the snippet source is really long (try e.g. http://localhost:8083/r5), then the window is larger than the page. Can you make set `max-height` (or something) to, say 80% of the window and enable scrollbars (and also make it a bit wider for copying source)?

Nice work :) looking forward to having this merged!

**Comment by abjrcode** [comment]
Thanks. I haven't been around any sort of web development for two years now, so I had to read about all those technologies in a short amount of time, thus you might find my coding style especially with JavaScript a bit crappy.
- As for the **Copy source** button on your machine. I suspect you need to change the the URL targeted by the AJAX request in the **copyContent.js**:  
  `var snippetSourceUrl = 'http://localhost:8083/raw/' + snippetId;`
  according to the build you are running as you might by getting a _not the same origin exception_. If that is not the case then please check your browser's console for any JavaScript errors or warnings. What browser are you using by the way ?
- Regarding the above error, I think these URLs along with other configuration should be loaded during build conditionally depending on target, I will look further into this.
- I will definitely look into the sizing issue. One thing Tomas. I would appreciate if you can test this with multiple browsers as my dev machine is a bit slow and can't handle installing multiple browsers. Thank you.

**Comment by abjrcode** [comment]
Hi Tomas.  

The modal size is now dynamically adjusted.  
This leaves the other problem with source. What's up with that ?  
Another thing: How do you access the HttpRequest from inside a template page ? I couldn't find that in Suave documentation.

**Comment by tpetricek** [comment]
I have not yet looked into the problem with source. Does this work for you?

As for accessing the HTTP request info, this is not automatically exposed to the template page. You need to modify the F# record that is passed to the template (see [this piece of code](https://github.com/tpetricek/FsSnip.Website/blob/master/code/pages/snippet.fs#L30)) and pass all data that you need there.

[Here is an example](https://github.com/tpetricek/NDC.Chat/blob/master/app.fsx#L77) that shows how to extract the body of a HTTP request and how to access URL parameters.

**Comment by abjrcode** [comment]
Yes. showing the source works perfectly on my device.

Could You check your browser's console for any JavaScript exceptions ?

**Comment by abjrcode** [comment]
Hey Tomas.

I have pushed another commit which should fix the issue completely.

Please let me know about the "show source" problem on your machine.

**Comment by tpetricek** [comment]
It took a long time (holidays + work!) but I finally deployed this to Azure: http://fssnip.azurewebsites.net/
The script seems to be working fine in Chrome, but there is something broken in IE (at least on my machine)

Also, now that it's running on Azure, it will be a lot more fun to complete the rest - any PR into master will immediately affect the web site!

**Pull request merged**
