### PR TITLE
fix for Copy Source display doesn't display all source code

### PR DESCRIPTION
**Pull request by mertoldi**
escape html <> so <paramarray> does not disappear when source is viewed
from copy source

### CODE REVIEW

**Comment by tpetricek** [comment]
Just wondering - isn't there some built-in JS function for this that would handle more elaborate cases too?

**Comment by mertoldi** [comment]
I'll have a look

**Comment by michaelbertoldi** [comment]
ok , change made , using jquery text instead

**Comment by mertoldi** [comment]
changed to use some jquery instead

**Comment by tpetricek** [comment]
Aaah, using `text` sounds like a good plan :)

I have one more question though - doesn't adding `find` change on which element are the subsequent `css` calls applied? (I'm not sure if this matters, but I guess it would apply `max-height` and `overflow-y` on the `<pre>` element now, but on the `<div>` element before?)

**Comment by mertoldi** [comment]
i've added another version, this should leave the css as it was before.

**Comment by tpetricek** [comment]
Thanks for bearing with me :) this looks great - merging now.

**Pull request merged**
