### PR TITLE
Find first free port

### PR DESCRIPTION
**Pull request by forki**
You don't want to conflict with stuff like fsreveal ;-)

### CODE REVIEW

**Comment by tpetricek** [comment]
This should really be the default in all those scripts! :)

Thanks a lot for the tweak, it's now merged.

**Comment by tpetricek** [comment]
Oops, this did not quite work. It breaks the Azure deployment with:

> System.Net.NetworkInformation.NetworkInformationException (0x80004005): Access is denied

I fixed this, because all we really needed is to only call `findPort` from the `run` target (there is another target that's run on Azure when deploying - this is perhaps not optimal, because we're mixing two things in a single file...)

**Comment by forki** [comment]
so it's ok now?

**Comment by tpetricek** [comment]
Yes, it's ok now, sorry for unclear comment :)

**Pull request merged**
